const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'onehub-'));const port=32000+Math.floor(Math.random()*10000),admin='WXYZ-2345-6789-ABCD';let child,origin;
const common={PORT:String(port),NODE_ENV:'development',ADMIN_KEY:admin,KEY_ENCRYPTION_SECRET:'e'.repeat(40),KEY_LOOKUP_SECRET:'l'.repeat(40),SESSION_SECRET:'s'.repeat(40),DATA_DIR:tmp};
const req=(url,body,cookie='',csrf='')=>fetch(origin+url,{method:body?'POST':'GET',headers:{...(body?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{}),...(csrf?{'x-csrf-token':csrf}:{})},body:body?JSON.stringify(body):undefined});
function cookies(r){return r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')}
before(async()=>{child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,...common},stdio:'ignore'});origin=`http://127.0.0.1:${port}`;for(let i=0;i<80;i++){try{const r=await fetch(origin+'/api/session');if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('server did not start')});
after(()=>{child?.kill('SIGTERM');fs.rmSync(tmp,{recursive:true,force:true})});
test('верный ключ администратора открывает сессию, неверный отклоняется',async()=>{let r=await req('/api/login',{key:'ZZZZ-ZZZZ-ZZZZ-ZZZZ'});assert.equal(r.status,401);r=await req('/api/login',{key:admin});assert.equal(r.status,200);assert.equal((await r.json()).user.role,'admin')});
test('пользователь не получает доступ к административному API; статья очищается от script',async()=>{let r=await req('/api/login',{key:admin});const adminCookie=cookies(r),adminData=await r.json();r=await fetch(origin+'/api/users',{method:'POST',headers:{cookie:adminCookie,'content-type':'application/json','x-csrf-token':adminData.csrf},body:JSON.stringify({name:'Тестовый участник',deviceLimit:1})});assert.equal(r.status,201);const {key}=await r.json();r=await fetch(origin+'/api/articles',{method:'POST',headers:{cookie:adminCookie,'content-type':'application/json','x-csrf-token':adminData.csrf},body:JSON.stringify({title:'Проверка HTML',description:'Демо',status:'published',html:'<p>текст</p><script>alert(1)</script><a href=javascript:alert(1) onclick=alert(2)>опасная ссылка</a>'})});assert.equal(r.status,201);const pub=await r.json();assert.doesNotMatch(pub.article.html,/script|javascript|onclick/i);r=await req('/api/login',{key});assert.equal(r.status,200);const userCookie=cookies(r),userData=await r.json();r=await fetch(origin+'/api/users',{headers:{cookie:userCookie}});assert.equal(r.status,403);r=await fetch(origin+'/api/articles',{headers:{cookie:userCookie}});assert.equal(r.status,200);assert.equal((await r.json()).articles.some(a=>a.id===pub.article.id),true);assert.ok(userData.csrf)});
test('CSRF-токен обязателен для изменений',async()=>{const r=await req('/api/login',{key:admin}),cookie=cookies(r);const x=await fetch(origin+'/api/users',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({name:'Без CSRF'})});assert.equal(x.status,403)});
test('лимит устройств отклоняет второй браузер; замена ключа отзывает старый',async()=>{let r=await req('/api/login',{key:admin}),ac=cookies(r),ad=await r.json();r=await fetch(origin+'/api/users',{method:'POST',headers:{cookie:ac,'content-type':'application/json','x-csrf-token':ad.csrf},body:JSON.stringify({name:'Лимитированный',deviceLimit:1})});const created=await r.json(),oldKey=created.key;r=await req('/api/login',{key:oldKey});assert.equal(r.status,200);const userCookie=cookies(r);r=await req('/api/login',{key:oldKey});assert.equal(r.status,401);r=await fetch(origin+'/api/users/'+created.user.id,{method:'PATCH',headers:{cookie:ac,'content-type':'application/json','x-csrf-token':ad.csrf},body:JSON.stringify({rotate:true})});assert.equal(r.status,200);const {key:newKey}=await r.json();r=await req('/api/login',{key:oldKey});assert.equal(r.status,401);r=await req('/api/login',{key:newKey},userCookie);assert.equal(r.status,200);const ck=cookies(r);assert.ok(ck.includes('oh_session='));assert.ok(userCookie.includes('oh_device='));r=await fetch(origin+'/api/users/'+created.user.id,{headers:{cookie:ac}});const details=await r.json(),device=details.devices[0];r=await fetch(origin+'/api/devices/'+device.id,{method:'PATCH',headers:{cookie:ac,'content-type':'application/json','x-csrf-token':ad.csrf},body:JSON.stringify({blocked:true})});assert.equal(r.status,200);r=await fetch(origin+'/api/articles',{headers:{cookie:ck}});assert.equal(r.status,401)});

test('черновики и скрытые категории недоступны пользователю; удаление категории со статьями защищено',async()=>{
 let r=await req('/api/login',{key:admin}),adminCookie=cookies(r),adminSession=await r.json(),csrf=adminSession.csrf;
 const post=async(url,data)=>fetch(origin+url,{method:'POST',headers:{cookie:adminCookie,'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify(data)});
 r=await post('/api/categories',{name:'Секретная зона',slug:'secret-zone',hidden:true});assert.equal(r.status,201);const {category}=await r.json();
 r=await post('/api/articles',{title:'Скрытая статья',slug:'secret-article',categoryId:category.id,status:'draft',html:'<h2><span>Заголовок</span><br></h2><p></p><script>alert(1)</script><img src=x onerror=alert(2)>'});assert.equal(r.status,201);const created=await r.json();assert.doesNotMatch(created.article.html,/script|onerror/i);
 r=await fetch(origin+`/api/categories/${category.id}`,{method:'DELETE',headers:{cookie:adminCookie,'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({})});assert.equal(r.status,409);
 r=await post('/api/categories',{name:'Перенос',slug:'move-target'});const target=(await r.json()).category;r=await fetch(origin+`/api/categories/${category.id}`,{method:'DELETE',headers:{cookie:adminCookie,'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify({targetCategoryId:target.id})});assert.equal(r.status,200);r=await fetch(origin+'/api/categories/move-target/articles',{headers:{cookie:adminCookie}});assert.equal((await r.json()).articles.some(a=>a.slug==='secret-article'),true);
 r=await post('/api/users',{name:'Проверяющий',deviceLimit:2});const {key}=await r.json();r=await req('/api/login',{key});const userCookie=cookies(r);
 r=await fetch(origin+'/api/articles',{headers:{cookie:userCookie}});assert.equal(r.status,200);assert.equal((await r.json()).articles.some(a=>a.slug==='secret-article'),false);
 r=await fetch(origin+'/api/articles/secret-article',{headers:{cookie:userCookie}});assert.equal(r.status,404);
 r=await fetch(origin+'/api/categories',{headers:{cookie:userCookie}});assert.equal((await r.json()).categories.some(c=>c.slug==='secret-zone'),false);
 r=await fetch(origin+'/api/categories/secret-zone/articles',{headers:{cookie:userCookie}});assert.equal(r.status,404);
});

test('доступная опубликованная статья очищает опасную разметку и сохраняет относительный адрес категории',async()=>{
 let r=await req('/api/login',{key:admin}),adminCookie=cookies(r),ss=await r.json();const headers={cookie:adminCookie,'content-type':'application/json','x-csrf-token':ss.csrf};
 r=await fetch(origin+'/api/categories',{method:'POST',headers,body:JSON.stringify({name:'VPN',slug:'vpn'})});const {category}=await r.json();
 r=await fetch(origin+'/api/articles',{method:'POST',headers,body:JSON.stringify({title:'Инструкция',slug:'vpn-guide',categoryId:category.id,status:'published',html:'<p>Нормально</p><a href="javascript:alert(1)">ссылка</a><script>alert(1)</script>'})});assert.equal(r.status,201);
 r=await fetch(origin+'/api/articles/vpn-guide',{headers:{cookie:adminCookie}});const article=(await r.json()).article;assert.equal(article.categorySlug,'vpn');assert.match(article.html,/Нормально/);assert.doesNotMatch(article.html,/javascript|script/i);
 r=await fetch(origin+'/api/articles',{method:'POST',headers,body:JSON.stringify({title:'Не сохранять base64',slug:'base64-test',categoryId:category.id,content:{type:'doc',content:[{type:'image',attrs:{src:'data:image/png;base64,AAAA'}}]}})});assert.equal(r.status,400);
});

test('загрузка проверяет содержимое изображения и сохраняет оптимизированный WebP',async()=>{const sharp=require('sharp');const login=await req('/api/login',{key:admin}),cookie=cookies(login),ss=await login.json(),headers={cookie,'content-type':'application/json','x-csrf-token':ss.csrf};let r=await fetch(origin+'/api/uploads',{method:'POST',headers,body:JSON.stringify({type:'image/png',data:'data:image/png;base64,SGVsbG8='})});assert.equal(r.status,400);const png=await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer();r=await fetch(origin+'/api/uploads',{method:'POST',headers,body:JSON.stringify({type:'image/png',data:`data:image/png;base64,${png.toString('base64')}`})});assert.equal(r.status,201);assert.match((await r.json()).url,/\.webp$/)});
test('скрипт выдаётся только выбранному активному пользователю, reset public_id отзывает ссылку, user не админ',async()=>{
 let r=await req('/api/login',{key:admin}),ac=cookies(r),as=await r.json(),headers={cookie:ac,'content-type':'application/json','x-csrf-token':as.csrf};
 r=await fetch(origin+'/api/scripts',{method:'POST',headers,body:JSON.stringify({title:'Тестовый установщик',slug:'test_script',description:'demo'})});assert.equal(r.status,201);const {script}=await r.json();
 r=await fetch(origin+`/api/scripts/${script.id}/draft`,{method:'PUT',headers,body:JSON.stringify({content:'#!/usr/bin/env bash\nset -euo pipefail\nprintf "%s\\n" {{USER_PUBLIC_ID}} {{SCRIPT_VERSION}}\n'})});assert.equal(r.status,200);
 r=await fetch(origin+`/api/scripts/${script.id}/publish`,{method:'POST',headers,body:JSON.stringify({comment:'initial'})});assert.equal(r.status,201);const version=await r.json();assert.equal(version.version.sha256.length,64);
 r=await fetch(origin+'/api/users',{method:'POST',headers,body:JSON.stringify({name:'Script User'})});assert.equal(r.status,201);const created=await r.json();
 r=await req('/api/login',{key:created.key});const uc=cookies(r);r=await fetch(origin+'/api/scripts',{headers:{cookie:uc}});assert.equal(r.status,403);
 r=await fetch(origin+`/api/scripts/${script.id}/access`,{method:'PUT',headers,body:JSON.stringify({mode:'selected',userIds:[]})});assert.equal(r.status,200);
 r=await fetch(origin+'/api/users/'+created.user.id,{headers});const details=await r.json(),oldId=details.user.public_id,denied=await fetch(origin+`/u/${oldId}/script/test_script.sh`);assert.equal(denied.status,404);const unknown=await fetch(origin+`/u/${'A'.repeat(22)}/script/test_script.sh`);assert.equal(unknown.status,404);assert.equal(await unknown.text(),await denied.text());
 r=await fetch(origin+`/api/scripts/${script.id}/access`,{method:'PUT',headers,body:JSON.stringify({mode:'selected',userIds:[created.user.id]})});assert.equal(r.status,200);r=await fetch(origin+`/api/scripts/${script.id}`,{method:'PATCH',headers,body:JSON.stringify({verifyEnabled:true,reportEnabled:true})});assert.equal(r.status,200);
 r=await fetch(origin+`/u/${oldId}/script/test_script.sh`);assert.equal(r.status,200);const text=await r.text();assert.match(text,/one\/\/hub/);assert.match(text,new RegExp(oldId));assert.match(text,/v1/);assert.equal(r.headers.get('content-type'),'text/plain; charset=utf-8');assert.match(text,/Optional access verification/);assert.match(text,/Optional installation report/);const {spawnSync}=require('node:child_process'),bashCheck=spawnSync('bash',['-n'],{input:text,encoding:'utf8'});assert.equal(bashCheck.status,0,bashCheck.stderr);
 r=await fetch(origin+`/api/users/${created.user.id}/public-id`,{method:'POST',headers,body:JSON.stringify({})});assert.equal(r.status,200);const newId=(await r.json()).public_id;assert.notEqual(oldId,newId);
 const oldAgain=await fetch(origin+`/u/${oldId}/script/test_script.sh`),newNow=await fetch(origin+`/u/${newId}/script/test_script.sh`);assert.equal(oldAgain.status,404);assert.equal(newNow.status,200);
});

test('превышение лимита входов блокируется после серии попыток',async()=>{let r,locked=false;for(let i=0;i<10&&!locked;i++){r=await req('/api/login',{key:'AAAA-AAAA-AAAA-AAAA'});locked=r.status===429}assert.equal(locked,true)});
