const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'onehub-'));const port=32000+Math.floor(Math.random()*10000),admin='WXYZ-2345-6789-ABCD';let child,origin;
const common={PORT:String(port),NODE_ENV:'development',ADMIN_KEY:admin,KEY_ENCRYPTION_SECRET:'e'.repeat(40),KEY_LOOKUP_SECRET:'l'.repeat(40),SESSION_SECRET:'s'.repeat(40),DATA_DIR:tmp};
const req=(url,body,cookie='',csrf='')=>fetch(origin+url,{method:body?'POST':'GET',headers:{...(body?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{}),...(csrf?{'x-csrf-token':csrf}:{})},body:body?JSON.stringify(body):undefined});
function cookies(r){return r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')}
before(async()=>{child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,...common},stdio:'ignore'});origin=`http://127.0.0.1:${port}`;for(let i=0;i<80;i++){try{const r=await fetch(origin+'/api/session');if(r.ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw Error('server did not start')});
after(()=>{child?.kill('SIGTERM');fs.rmSync(tmp,{recursive:true,force:true})});
test('верный ключ администратора открывает сессию, неверный отклоняется',async()=>{let r=await req('/api/login',{key:'ZZZZ-ZZZZ-ZZZZ-ZZZZ'});assert.equal(r.status,401);r=await req('/api/login',{key:admin});assert.equal(r.status,200);assert.equal((await r.json()).user.role,'admin')});
test('пользователь не получает доступ к административному API; статья очищается от script',async()=>{let r=await req('/api/login',{key:admin});const adminCookie=cookies(r),adminData=await r.json();r=await fetch(origin+'/api/users',{method:'POST',headers:{cookie:adminCookie,'content-type':'application/json','x-csrf-token':adminData.csrf},body:JSON.stringify({name:'Тестовый участник',deviceLimit:1})});assert.equal(r.status,201);const {key}=await r.json();r=await fetch(origin+'/api/articles',{method:'POST',headers:{cookie:adminCookie,'content-type':'application/json','x-csrf-token':adminData.csrf},body:JSON.stringify({title:'Проверка HTML',description:'Демо',status:'published',html:'<p>текст</p><script>alert(1)</script><a href=javascript:alert(1) onclick=alert(2)>опасная ссылка</a>'})});assert.equal(r.status,201);const pub=await r.json();assert.doesNotMatch(pub.article.html,/script|javascript|onclick/i);r=await req('/api/login',{key});assert.equal(r.status,200);const userCookie=cookies(r),userData=await r.json();r=await fetch(origin+'/api/users',{headers:{cookie:userCookie}});assert.equal(r.status,403);r=await fetch(origin+'/api/articles',{headers:{cookie:userCookie}});assert.equal(r.status,200);assert.equal((await r.json()).articles.some(a=>a.id===pub.article.id),true);assert.ok(userData.csrf)});
test('CSRF-токен обязателен для изменений',async()=>{const r=await req('/api/login',{key:admin}),cookie=cookies(r);const x=await fetch(origin+'/api/users',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({name:'Без CSRF'})});assert.equal(x.status,403)});
test('лимит устройств отклоняет второй браузер; замена ключа отзывает старый',async()=>{let r=await req('/api/login',{key:admin}),ac=cookies(r),ad=await r.json();r=await fetch(origin+'/api/users',{method:'POST',headers:{cookie:ac,'content-type':'application/json','x-csrf-token':ad.csrf},body:JSON.stringify({name:'Лимитированный',deviceLimit:1})});const created=await r.json(),oldKey=created.key;r=await req('/api/login',{key:oldKey});assert.equal(r.status,200);const userCookie=cookies(r);r=await req('/api/login',{key:oldKey});assert.equal(r.status,401);r=await fetch(origin+'/api/users/'+created.user.id,{method:'PATCH',headers:{cookie:ac,'content-type':'application/json','x-csrf-token':ad.csrf},body:JSON.stringify({rotate:true})});assert.equal(r.status,200);const {key:newKey}=await r.json();r=await req('/api/login',{key:oldKey});assert.equal(r.status,401);r=await req('/api/login',{key:newKey},userCookie);assert.equal(r.status,200);const ck=cookies(r);assert.ok(ck.includes('oh_session='));assert.ok(userCookie.includes('oh_device='));r=await fetch(origin+'/api/users/'+created.user.id,{headers:{cookie:ac}});const details=await r.json(),device=details.devices[0];r=await fetch(origin+'/api/devices/'+device.id,{method:'PATCH',headers:{cookie:ac,'content-type':'application/json','x-csrf-token':ad.csrf},body:JSON.stringify({blocked:true})});assert.equal(r.status,200);r=await fetch(origin+'/api/articles',{headers:{cookie:ck}});assert.equal(r.status,401)});
test('превышение лимита входов блокируется после серии попыток',async()=>{let r,locked=false;for(let i=0;i<10&&!locked;i++){r=await req('/api/login',{key:'AAAA-AAAA-AAAA-AAAA'});locked=r.status===429}assert.equal(locked,true)});
