const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {sanitize: sanitizeContent} = require('./lib/content');
const sharp = require('sharp');
const {z} = require('zod');

function loadEnv() {
  try { for (const line of fs.readFileSync('.env', 'utf8').split(/\r?\n/)) { const m=line.match(/^\s*([A-Z_]+)\s*=\s*(.*?)\s*$/); if(m&&!process.env[m[1]]) process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,''); } } catch {}
}
loadEnv();
const PORT = Number(process.env.PORT || 3000), HOST = process.env.HOST || '127.0.0.1', PROD = process.env.NODE_ENV === 'production';
const keyRe = /^(?!.*[O01I])[A-HJ-NP-Z2-9]{4}(?:-[A-HJ-NP-Z2-9]{4}){3}$/;
const categorySchema=z.object({name:z.string().trim().min(1).max(100),slug:z.string().max(120).regex(/^[a-z0-9-]+$/).optional(),description:z.string().max(500).optional(),icon:z.string().max(12000).optional(),hidden:z.boolean().optional()});
const sanitizeSvgIcon=(value='')=>{const raw=String(value||'').slice(0,12000);if(!/^\s*<svg\b/i.test(raw))return raw.slice(0,32);return require('sanitize-html')(raw,{allowedTags:['svg','g','path','circle','rect','line','polyline','polygon','ellipse'],allowedAttributes:{svg:['viewbox','width','height','fill','stroke','stroke-width','role','aria-hidden'],g:['fill','stroke','stroke-width','transform'],path:['d','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','fill-rule'],circle:['cx','cy','r','fill','stroke','stroke-width'],rect:['x','y','width','height','rx','ry','fill','stroke','stroke-width'],line:['x1','y1','x2','y2','stroke','stroke-width'],polyline:['points','fill','stroke','stroke-width'],polygon:['points','fill','stroke','stroke-width'],ellipse:['cx','cy','rx','ry','fill','stroke','stroke-width']},allowedSchemes:[]})};
const tiptapNode=z.lazy(()=>z.object({type:z.string().max(40),attrs:z.record(z.unknown()).optional(),text:z.string().max(500000).optional(),marks:z.array(z.object({type:z.string().max(40),attrs:z.record(z.unknown()).optional()}).passthrough()).max(24).optional(),content:z.array(tiptapNode).max(10000).optional()}).passthrough());
const articleSchema=z.object({title:z.string().trim().min(1).max(180),slug:z.string().max(100).regex(/^[a-z0-9-]+$/).optional(),description:z.string().max(400).optional(),categoryId:z.string().optional(),status:z.enum(['draft','published']).optional(),hidden:z.boolean().optional(),html:z.string().max(500000).optional(),content:tiptapNode.optional(),cover:z.string().max(1000).optional(),seoTitle:z.string().max(1000).optional(),metaDescription:z.string().max(1000).optional(),outline:z.array(z.object({id:z.string().regex(/^section-[a-f0-9]{16,}$/),text:z.string().trim().min(1).max(120)})).max(100).optional()}).passthrough();
const adminKey=process.env.ADMIN_KEY || '', required=['KEY_ENCRYPTION_SECRET','KEY_LOOKUP_SECRET','SESSION_SECRET'];
if(!keyRe.test(adminKey) || adminKey==='ABCD-EFGH-JKLM-NPQR') throw new Error('ADMIN_KEY отсутствует, имеет неверный формат или совпадает с шаблоном. Настройте .env.');
for(const k of required) if(!process.env[k]||process.env[k].length<32||process.env[k].startsWith('replace-')) throw new Error(`${k} должен содержать не менее 32 случайных символов.`);
const derive=(s)=>crypto.createHash('sha256').update(s).digest();
const encKey=derive(process.env.KEY_ENCRYPTION_SECRET), lookupKey=derive(process.env.KEY_LOOKUP_SECRET), sessionSecret=derive(process.env.SESSION_SECRET);
const dataDir=path.resolve(process.env.DATA_DIR||path.join(__dirname,'data')); fs.mkdirSync(dataDir,{recursive:true});
const dbPath=path.join(dataDir,'store.json');
let db;
try { db=JSON.parse(fs.readFileSync(dbPath,'utf8')); } catch { db={users:[],articles:[],sessions:[],devices:[],logins:[],audit:[]}; }
for(const k of ['users','articles','sessions','devices','logins','audit','categories']) db[k] ||= [];
const articleDir=path.join(dataDir,'articles'), uploadDir=path.join(dataDir,'uploads');
fs.mkdirSync(articleDir,{recursive:true}); fs.mkdirSync(uploadDir,{recursive:true});
let migrated=false;
for(const a of db.articles){const file=path.join(articleDir,`${a.id}.html`);let oldHtml=a.html;if(!fs.existsSync(file)&&oldHtml){}else if(fs.existsSync(file))oldHtml=fs.readFileSync(file,'utf8');if(oldHtml!==undefined){const clean=sanitize(oldHtml);if(clean!==oldHtml||!fs.existsSync(file))fs.writeFileSync(file,clean,{mode:0o600});if(a.html){delete a.html;migrated=true}}}
if(!db.categories.length){const c={id:id(),name:'Без категории',slug:'bez-kategorii',description:'',icon:'◈',sort_order:0,hidden:false,created:new Date().toISOString()};db.categories.push(c);for(const a of db.articles)if(!a.categoryId)a.categoryId=c.id;migrated=true}
for(let i=0;i<db.categories.length;i++){const c=db.categories[i];c.slug ||= slugify(c.name)||`category-${i+1}`;c.description ||= '';c.icon=sanitizeSvgIcon(c.icon||'◈');c.sort_order ??= i;c.hidden=!!c.hidden;}
for(const a of db.articles)if(!a.categoryId){a.categoryId=db.categories[0].id;migrated=true}
if(migrated)save();
function save(){ fs.writeFileSync(dbPath,JSON.stringify(db,null,2),{mode:0o600}); }
function id(){return crypto.randomUUID()}
function digest(key){return crypto.createHmac('sha256',lookupKey).update(key).digest('hex')}
function encrypt(text){const iv=crypto.randomBytes(12), c=crypto.createCipheriv('aes-256-gcm',encKey,iv), data=Buffer.concat([c.update(text),c.final()]);return [iv.toString('base64'),c.getAuthTag().toString('base64'),data.toString('base64')].join('.')}
function decrypt(value){const [iv,tag,data]=value.split('.');const d=crypto.createDecipheriv('aes-256-gcm',encKey,Buffer.from(iv,'base64'));d.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([d.update(Buffer.from(data,'base64')),d.final()]).toString()}
function safeEqual(a,b){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function safeTiptap(node,depth=0){if(!node||typeof node!=='object'||depth>64)return false;for(const mark of node.marks||[]){if(mark.type==='link'&&!/^(?:https?:\/\/|mailto:)/i.test(String(mark.attrs?.href||'')))return false}return !Array.isArray(node.content)||node.content.length<=10000&&node.content.every(child=>safeTiptap(child,depth+1))}
function makeKey(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789', bytes=crypto.randomBytes(16), raw=[...bytes].map(x=>chars[x%chars.length]).join('');return raw.match(/.{4}/g).join('-')}
function slugify(s){const map={а:'a',б:'b',в:'v',г:'g',д:'d',е:'e',ё:'e',ж:'zh',з:'z',и:'i',й:'y',к:'k',л:'l',м:'m',н:'n',о:'o',п:'p',р:'r',с:'s',т:'t',у:'u',ф:'f',х:'h',ц:'ts',ч:'ch',ш:'sh',щ:'sch',ъ:'',ы:'y',ь:'',э:'e',ю:'yu',я:'ya'};return String(s||'').toLowerCase().replace(/[а-яё]/g,c=>map[c]??c).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function cookie(req,name){const s=req.headers.cookie||'';const m=s.match(new RegExp('(?:^|; )'+name+'=([^;]*)'));return m?decodeURIComponent(m[1]):''}
function ip(req){return process.env.TRUST_PROXY==='true'?(req.headers['x-forwarded-for']||'').split(',')[0].trim()||req.socket.remoteAddress:req.socket.remoteAddress}
function ua(req){const s=req.headers['user-agent']||'Неизвестное устройство';return s.slice(0,220)}
function log(event, actor, address, detail=''){db.audit.unshift({id:id(),event,actor,address,detail,at:new Date().toISOString()});db.audit=db.audit.slice(0,500);save()}
function send(res,status,body,headers={}){const isText=typeof body==='string',isBinary=Buffer.isBuffer(body);const b=isText||isBinary?body:JSON.stringify(body);res.writeHead(status,{'content-type':isText?'text/html; charset=utf-8':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(b)}
function fail(res,status,message){send(res,status,{error:message})}
function session(req){const raw=cookie(req,'oh_session');if(!raw)return null;const [sid,mac]=raw.split('.');if(!sid||!mac||!safeEqual(mac,crypto.createHmac('sha256',sessionSecret).update(sid).digest('hex')))return null;const s=db.sessions.find(x=>x.id===sid&&x.expires>Date.now());if(!s)return null;s.lastSeen=Date.now();return s}
function userFor(s){return s?.role==='admin'?{id:'admin',name:'Администратор',role:'admin'}:db.users.find(x=>x.id===s?.userId)}
function csrfOk(req,s){return s&&safeEqual(req.headers['x-csrf-token']||'',s.csrf)}
const fails=new Map();
function authCookie(sid){const mac=crypto.createHmac('sha256',sessionSecret).update(sid).digest('hex');return `oh_session=${sid}.${mac}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${PROD?'; Secure':''}`}
function deviceCookie(raw){return `oh_device=${raw}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${PROD?'; Secure':''}`}
function sanitize(html){return sanitizeContent(html)}
async function body(req){let raw='';for await(const c of req){raw+=c;if(raw.length>7200000)throw new Error('Слишком большой запрос.')}try{return JSON.parse(raw||'{}')}catch{throw new Error('Некорректный JSON.') }}
function articleHtml(a){try{return fs.readFileSync(path.join(articleDir,`${a.id}.html`),'utf8')}catch{return a.html||''}}
function articleText(a){return articleHtml(a).replace(/<[^>]*>/g,' ').replace(/&(?:nbsp|amp|lt|gt|quot|#39);/g,' ').replace(/\s+/g,' ')}
function saveArticleHtml(a,html){fs.writeFileSync(path.join(articleDir,`${a.id}.html`),sanitize(html),{mode:0o600});delete a.html}
function articleContent(a){try{return JSON.parse(fs.readFileSync(path.join(articleDir,`${a.id}.json`),'utf8'))}catch{return a.content||null}}
function publicArticle(a){const c=db.categories.find(c=>c.id===a.categoryId);return {id:a.id,title:a.title,slug:a.slug,description:a.description,cover:a.cover?.trim().startsWith('<svg')?sanitizeSvgIcon(a.cover):a.cover,status:a.status,hidden:!!a.hidden,categoryId:a.categoryId||'',categoryName:c?.name||'Без категории',categorySlug:c?.slug||'',content:articleContent(a),html:articleHtml(a),updated:a.updated,created:a.created,seoTitle:a.seoTitle||'',metaDescription:a.metaDescription||'',outline:Array.isArray(a.outline)?a.outline:[]}}
function seed(){if(db.users.length||db.articles.length)return;const u=[['Мария Волкова',3],['Илья Смирнов',2],['Анна Лебедева',2]], issued=[];for(const [name,limit] of u){const k=makeKey();issued.push({name,key:k});db.users.push({id:id(),name,note:'Демонстрационный аккаунт',deviceLimit:limit,blocked:false,keyHash:digest(k),keyEncrypted:encrypt(k),created:new Date().toISOString()});}
const articles=[['Как читать вдумчиво','Приёмы, которые помогают замечать главное и сохранять идеи.','Развитие'],['Рабочее пространство без шума','Небольшие привычки, которые возвращают внимание к важному.','Практика'],['Заметки, к которым возвращаются','Как превратить разрозненные мысли в живую систему знаний.','Знания']];
for(let i=0;i<articles.length;i++){const [title,description,tag]=articles[i];db.articles.push({id:id(),title,slug:'article-'+(i+1),description,cover:'',status:'published',html:`<p>${description}</p><h2>${tag}</h2><p>Хорошая система начинается с простого шага. Выберите одну идею, проверьте её на практике и сохраните выводы в месте, куда легко вернуться.</p><blockquote>Полезное знание — то, которое меняет следующий шаг.</blockquote><p>Возвращайтесь к заметке, дополняйте её новыми наблюдениями и делитесь результатом.</p>`,created:new Date(Date.now()-i*86400000*4).toISOString(),updated:new Date().toISOString(),seoTitle:title,metaDescription:description});}save();console.log('Демо-ключи пользователей (показываются только при первичном создании):');for(const x of issued)console.log(`${x.name}: ${x.key}`)}
if(process.argv.includes('--seed')){if(!PROD)seed();else console.error('Сид-данные разрешены только в dev-режиме.');process.exit(PROD?1:0)}
const server=http.createServer(async(req,res)=>{
res.setHeader('x-content-type-options','nosniff');res.setHeader('referrer-policy','no-referrer');res.setHeader('x-frame-options','DENY');res.setHeader('permissions-policy','camera=(), microphone=(), geolocation=()');res.setHeader('content-security-policy',"default-src 'self'; img-src 'self' https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com; script-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'");if(PROD)res.setHeader('strict-transport-security','max-age=31536000; includeSubDomains');
const url=new URL(req.url,'http://localhost'), route=url.pathname, address=ip(req), s=session(req), me=userFor(s);
try{
if(req.method==='GET'&&route==='/api/session'){return send(res,200,{user:me||null,csrf:s?.csrf||null})}
if(req.method==='POST'&&route==='/api/login'){
const attempts=fails.get(address)||{count:0,until:0};if(Date.now()<attempts.until){await new Promise(r=>setTimeout(r,250));return fail(res,429,'Не удалось выполнить вход. Попробуйте позже.')}
const b=await body(req), candidate=String(b.key||'').toUpperCase().replace(/[^A-Z0-9]/g,'').match(/.{1,4}/g)?.join('-')||'';
const adminMatch=safeEqual(digest(candidate),digest(adminKey));let user=db.users.find(x=>safeEqual(x.keyHash,digest(candidate)));
let deviceRaw=cookie(req,'oh_device');if(!deviceRaw){deviceRaw=crypto.randomBytes(24).toString('hex');res.setHeader('Set-Cookie',deviceCookie(deviceRaw))}
let device=db.devices.find(d=>d.userId===user?.id&&d.tokenHash===digest(deviceRaw));
const valid=keyRe.test(candidate)&&(adminMatch||!!user&&!user.blocked);
if(valid&&user){if(device?.blocked) { await new Promise(r=>setTimeout(r,250));return fail(res,401,'Не удалось выполнить вход. Проверьте ключ или обратитесь к администратору.')}if(!device&&db.devices.filter(d=>d.userId===user.id&&!d.blocked).length>=user.deviceLimit){db.logins.unshift({id:id(),userId:user.id,ip:address,ua:ua(req),success:false,at:new Date().toISOString()});save();await new Promise(r=>setTimeout(r,250));return fail(res,401,'Не удалось выполнить вход. Проверьте ключ или обратитесь к администратору.')}
if(!device){device={id:id(),userId:user.id,tokenHash:digest(deviceRaw),ua:ua(req),ip:address,first:new Date().toISOString(),last:new Date().toISOString(),blocked:false};db.devices.push(device)}else {device.last=new Date().toISOString();device.ip=address}}
if(!valid){attempts.count++;attempts.until=attempts.count>=5?Date.now()+Math.min(60000,attempts.count*5000):0;fails.set(address,attempts);db.logins.unshift({id:id(),userId:user?.id||null,ip:address,ua:ua(req),success:false,at:new Date().toISOString()});log('Неудачный вход','неизвестно',address);await new Promise(r=>setTimeout(r,250));return fail(res,401,'Не удалось выполнить вход. Проверьте ключ или обратитесь к администратору.')}
fails.delete(address);const sid=id(),csrf=crypto.randomBytes(24).toString('hex');db.sessions=db.sessions.filter(x=>x.id!==s?.id);db.sessions.push({id:sid,role:adminMatch?'admin':'user',userId:user?.id,csrf,created:Date.now(),expires:Date.now()+12*60*60*1000});db.logins.unshift({id:id(),userId:user?.id||'admin',ip:address,ua:ua(req),success:true,at:new Date().toISOString()});log('Вход',adminMatch?'Администратор':user.name,address);save();const cookies=[authCookie(sid)];if(deviceRaw&&!cookie(req,'oh_device'))cookies.unshift(deviceCookie(deviceRaw));return send(res,200,{user:adminMatch?{id:'admin',name:'Администратор',role:'admin'}:{id:user.id,name:user.name,role:'user'},csrf},{'set-cookie':cookies})}
if(!route.startsWith('/api')){if(req.method!=='GET')return fail(res,404,'Не найдено.');if(route.startsWith('/uploads/')){if(!s||s.role==='user'&&(!me||me.blocked))return fail(res,401,'Требуется вход.');const file=path.basename(route);if(!/^[a-f0-9-]+\.(?:png|jpe?g|webp|gif)$/i.test(file))return fail(res,404,'Не найдено.');const fp=path.join(uploadDir,file);if(!fs.existsSync(fp))return fail(res,404,'Не найдено.');return send(res,200,fs.readFileSync(fp),{'content-type':({'png':'image/png','jpg':'image/jpeg','jpeg':'image/jpeg','webp':'image/webp','gif':'image/gif'})[path.extname(file).slice(1).toLowerCase()]||'application/octet-stream','cache-control':'private, max-age=31536000, immutable'})}const root=path.join(__dirname,'dist');if(!fs.existsSync(path.join(root,'index.html'))){res.setHeader('cache-control','no-store');return fail(res,503,'Production UI не собран. Выполните npm run build.')}let file=decodeURIComponent(route).replace(/^\/+/, '');const target=path.resolve(root,file||'index.html');if(!target.startsWith(root+path.sep)&&target!==path.join(root,'index.html'))return fail(res,404,'Не найдено.');if(!fs.existsSync(target)||fs.statSync(target).isDirectory()){if(path.extname(route))return fail(res,404,'Не найдено.');file='index.html'}const fp=path.join(root,file||'index.html');return send(res,200,fs.readFileSync(fp),{'content-type':fp.endsWith('.js')?'text/javascript; charset=utf-8':fp.endsWith('.css')?'text/css; charset=utf-8':fp.endsWith('.svg')?'image/svg+xml':fp.endsWith('.png')?'image/png':fp.endsWith('.webp')?'image/webp':'text/html; charset=utf-8','x-robots-tag':'noindex, nofollow'})}
if(s?.role==='user'&&(!me||me.blocked)){db.sessions=db.sessions.filter(x=>x.id!==s.id);save();return fail(res,401,'Доступ закрыт. Обратитесь к администратору.')}
if((route==='/api'||route.startsWith('/api/'))&&!s)return fail(res,401,'Требуется вход.');
if(route.startsWith('/api/')&&req.method!=='GET'&&!csrfOk(req,s))return fail(res,403,'Сеанс устарел. Обновите страницу.');
if(req.method==='POST'&&route==='/api/logout'){db.sessions=db.sessions.filter(x=>x.id!==s.id);save();return send(res,200,{ok:true},{'set-cookie':'oh_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'})}
if(req.method==='POST'&&route==='/api/logout-all'){if(s.role!=='admin')db.sessions=db.sessions.filter(x=>x.userId!==s.userId);else db.sessions=db.sessions.filter(x=>x.role!=='admin');save();return send(res,200,{ok:true},{'set-cookie':'oh_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'})}
if(route.startsWith('/api/')&&s.role==='user'&&!(req.method==='GET'&&(route==='/api/categories'||route.startsWith('/api/categories/'))) &&route!=='/api/articles'&&!route.startsWith('/api/articles/'))return fail(res,403,'Недостаточно прав.');
if(s.role==='user'&&db.devices.some(d=>d.userId===s.userId&&d.tokenHash===digest(cookie(req,'oh_device'))&&d.blocked)){db.sessions=db.sessions.filter(x=>x.id!==s.id);save();return fail(res,401,'Доступ к этому устройству закрыт.')}
if(req.method==='GET'&&route==='/api/categories'){const cats=db.categories.filter(c=>s.role==='admin'||!c.hidden).map(c=>({...c,count:s.role==='admin'?db.articles.filter(a=>a.categoryId===c.id).length:db.articles.filter(a=>a.categoryId===c.id&&a.status==='published'&&!a.hidden).length,publishedCount:db.articles.filter(a=>a.categoryId===c.id&&a.status==='published'&&!a.hidden).length})).filter(c=>s.role==='admin'||c.count>0).sort((a,b)=>a.sort_order-b.sort_order);return send(res,200,{categories:cats})}
if(req.method==='GET'&&route.startsWith('/api/categories/')&&route.endsWith('/articles')){const slug=route.split('/')[3],c=db.categories.find(x=>x.slug===slug);if(!c||s.role!=='admin'&&c.hidden)return fail(res,404,'Категория не найдена.');const articles=db.articles.filter(a=>a.categoryId===c.id&&(s.role==='admin'||a.status==='published'&&!a.hidden)).sort((a,b)=>b.updated.localeCompare(a.updated)).map(publicArticle);return send(res,200,{category:c,articles})}
if(s.role==='admin'&&req.method==='PUT'&&route==='/api/categories/order'){const b=await body(req);if(!Array.isArray(b.ids)||b.ids.length!==db.categories.length||new Set(b.ids).size!==db.categories.length||b.ids.some(x=>!db.categories.some(c=>c.id===x)))return fail(res,400,'Некорректный порядок категорий.');b.ids.forEach((x,i)=>db.categories.find(c=>c.id===x).sort_order=i);save();return send(res,200,{ok:true})}
if(s.role==='admin'&&req.method==='DELETE'&&route.startsWith('/api/categories/')){const c=db.categories.find(x=>x.id===route.split('/').pop());if(!c)return fail(res,404,'Категория не найдена.');const b=await body(req),items=db.articles.filter(a=>a.categoryId===c.id);if(items.length&&!b.targetCategoryId&&b.deleteArticles!==true)return fail(res,409,'Категория содержит статьи. Укажите категорию переноса или deleteArticles=true.');if(b.targetCategoryId){if(!db.categories.some(x=>x.id===b.targetCategoryId&&x.id!==c.id))return fail(res,400,'Категория переноса не найдена.');for(const a of items)a.categoryId=b.targetCategoryId}else if(b.deleteArticles===true){for(const a of items){db.articles=db.articles.filter(x=>x.id!==a.id);for(const ext of ['html','json'])try{fs.unlinkSync(path.join(articleDir,`${a.id}.${ext}`))}catch{}}}db.categories=db.categories.filter(x=>x.id!==c.id);save();return send(res,200,{ok:true})}
if(s.role==='admin'&&req.method==='POST'&&route==='/api/categories'){const parsed=categorySchema.safeParse(await body(req));if(!parsed.success)return fail(res,400,'Проверьте поля категории.');const b=parsed.data,name=String(b.name||'').trim().slice(0,100);if(!name)return fail(res,400,'Введите название категории.');if(db.categories.some(c=>c.name.toLocaleLowerCase('ru')===name.toLocaleLowerCase('ru')))return fail(res,409,'Такая категория уже существует.');const slug=String(b.slug||slugify(name));if(!slug||db.categories.some(c=>c.slug===slug))return fail(res,409,'Этот адрес категории уже занят.');const c={id:id(),name,slug,description:String(b.description||'').slice(0,500),icon:sanitizeSvgIcon(b.icon||'◈'),sort_order:db.categories.length,hidden:!!b.hidden,created:new Date().toISOString()};db.categories.push(c);save();return send(res,201,{category:c})}
if(s.role==='admin'&&req.method==='PATCH'&&route.startsWith('/api/categories/')){const c=db.categories.find(x=>x.id===route.split('/').pop());if(!c)return fail(res,404,'Категория не найдена.');const parsed=categorySchema.safeParse(await body(req));if(!parsed.success)return fail(res,400,'Проверьте поля категории.');const b=parsed.data,name=String(b.name||'').trim().slice(0,100);if(!name)return fail(res,400,'Введите название категории.');const slug=String(b.slug||slugify(name));if(db.categories.some(x=>x.id!==c.id&&(x.slug===slug||x.name.toLocaleLowerCase('ru')===name.toLocaleLowerCase('ru'))))return fail(res,409,'Название или адрес уже используются.');Object.assign(c,{name,slug,description:String((b.description??c.description)||'').slice(0,500),icon:sanitizeSvgIcon((b.icon??c.icon)||'◈'),hidden:b.hidden===undefined?c.hidden:!!b.hidden});save();return send(res,200,{category:c})}
if(s.role==='admin'&&req.method==='POST'&&route==='/api/uploads'){const b=await body(req),mime=String(b.type||'');if(!['image/png','image/jpeg','image/webp','image/gif'].includes(mime))return fail(res,400,'Поддерживаются PNG, JPEG, WebP и GIF.');const raw=String(b.data||'').replace(/^data:[^;]+;base64,/,'');if(raw.length>7000000)return fail(res,413,'Файл слишком большой (максимум 5 МБ).');const input=Buffer.from(raw,'base64');if(!input.length||input.length>5*1024*1024)return fail(res,413,'Файл пустой или превышает 5 МБ.');let output;try{const image=sharp(input,{limitInputPixels:40000000,animated:false});const meta=await image.metadata();if(!['png','jpeg','webp','gif'].includes(meta.format))return fail(res,400,'Формат содержимого не совпадает с изображением.');output=await image.rotate().resize({width:2400,height:2400,fit:'inside',withoutEnlargement:true}).webp({quality:82}).toBuffer()}catch{return fail(res,400,'Не удалось обработать изображение.')}const name=`${crypto.randomUUID()}.webp`;fs.writeFileSync(path.join(uploadDir,name),output,{mode:0o644,flag:'wx'});return send(res,201,{url:`/uploads/${name}`})}
if(req.method==='GET'&&route==='/api/articles'){const q=(url.searchParams.get('q')||'').toLocaleLowerCase('ru');let arr=db.articles.filter(a=>(s.role==='admin'||a.status==='published'&&!a.hidden)&&(!q||(a.title+' '+a.description+' '+articleText(a)).toLocaleLowerCase('ru').includes(q))&&(!url.searchParams.get('category')||a.categoryId===url.searchParams.get('category')));return send(res,200,{articles:arr.sort((a,b)=>b.updated.localeCompare(a.updated)).map(publicArticle),stats:{articles:db.articles.length,published:db.articles.filter(a=>a.status==='published').length,users:db.users.length}})}
if(route.startsWith('/api/articles/')&&req.method==='GET'){const key=route.split('/').pop(),a=db.articles.find(x=>x.id===key||x.slug===key);if(!a||s.role!=='admin'&&(a.status!=='published'||db.categories.find(c=>c.id===a.categoryId)?.hidden))return fail(res,404,'Статья не найдена.');return send(res,200,{article:publicArticle(a)})}
if(s.role==='admin'&&req.method==='POST'&&route==='/api/articles'){const parsed=articleSchema.safeParse(await body(req));if(!parsed.success)return fail(res,400,'Проверьте поля статьи.');const b=parsed.data;if(b.content&&!safeTiptap(b.content))return fail(res,400,'Документ содержит небезопасную ссылку.');const title=String(b.title||'').trim().slice(0,180);if(!title)return fail(res,400,'Укажите заголовок.');let slug=String(b.slug||slugify(title)).slice(0,100);if(!slug)slug='article-'+crypto.randomBytes(4).toString('hex');else if(db.articles.some(a=>a.slug===slug))slug=slug.slice(0,93)+'-'+crypto.randomBytes(3).toString('hex');const categoryId=String(b.categoryId||db.categories[0]?.id||'');if(!db.categories.some(c=>c.id===categoryId))return fail(res,400,'Сначала выберите категорию.');const a={id:id(),title,slug,description:String(b.description||'').slice(0,400),cover:(String(b.cover||'').trim().startsWith('<svg')?sanitizeSvgIcon(b.cover):String(b.cover||'')),categoryId,status:b.status==='published'?'published':'draft',hidden:!!b.hidden,created:new Date().toISOString(),updated:new Date().toISOString(),seoTitle:String(b.seoTitle||''),metaDescription:String(b.metaDescription||''),outline:Array.isArray(b.outline)?b.outline:[]};saveArticleHtml(a,b.html);if(b.content)fs.writeFileSync(path.join(articleDir,`${a.id}.json`),JSON.stringify(b.content),{mode:0o600});db.articles.unshift(a);save();log('Создание статьи',me.name,address,title);return send(res,201,{article:publicArticle(a)})}
if(s.role==='admin'&&route.startsWith('/api/articles/')&&req.method==='PUT'){const a=db.articles.find(x=>x.id===route.split('/').pop());if(!a)return fail(res,404,'Статья не найдена.');const parsed=articleSchema.partial().safeParse(await body(req));if(!parsed.success)return fail(res,400,'Проверьте поля статьи.');const b=parsed.data;if(b.content&&!safeTiptap(b.content))return fail(res,400,'Документ содержит небезопасную ссылку.');if(b.categoryId!==undefined&&!db.categories.some(c=>c.id===b.categoryId))return fail(res,400,'Выберите существующую категорию.');if(b.slug!==undefined){const slug=String(b.slug||slugify(b.title||a.title)).slice(0,100);if(db.articles.some(x=>x.id!==a.id&&x.slug===slug))return fail(res,409,'Этот адрес уже используется другой статьёй.');a.slug=slug}for(const k of ['title','description'])if(b[k]!==undefined)a[k]=String(b[k]).slice(0,k==='title'?180:400);if(b.html!==undefined)saveArticleHtml(a,b.html);if(b.content!==undefined)fs.writeFileSync(path.join(articleDir,`${a.id}.json`),JSON.stringify(b.content),{mode:0o600});for(const k of ['cover','seoTitle','metaDescription'])if(b[k]!==undefined)a[k]=k==='cover'&&String(b[k]).trim().startsWith('<svg')?sanitizeSvgIcon(b[k]):String(b[k]).slice(0,1000);if(b.outline!==undefined)a.outline=b.outline;if(b.status!==undefined)a.status=b.status==='published'?'published':'draft';if(b.hidden!==undefined)a.hidden=!!b.hidden;if(b.categoryId!==undefined)a.categoryId=b.categoryId;a.updated=new Date().toISOString();save();return send(res,200,{article:publicArticle(a)})}
if(s.role==='admin'&&route.startsWith('/api/articles/')&&req.method==='DELETE'){const removed=db.articles.find(x=>x.id===route.split('/').pop());db.articles=db.articles.filter(x=>x.id!==route.split('/').pop());if(removed)for(const ext of ['html','json'])try{fs.unlinkSync(path.join(articleDir,`${removed.id}.${ext}`))}catch{}save();log('Удаление статьи',me.name,address);return send(res,200,{ok:true})}
if(s.role==='admin'&&req.method==='POST'&&route.startsWith('/api/articles/')&&route.endsWith('/duplicate')){const original=db.articles.find(x=>x.id===route.split('/')[3]);if(!original)return fail(res,404,'Статья не найдена.');const a={...original,id:id(),title:`${original.title} — копия`,slug:`${original.slug.slice(0,90)}-copy-${crypto.randomBytes(2).toString('hex')}`,status:'draft',created:new Date().toISOString(),updated:new Date().toISOString()};db.articles.unshift(a);saveArticleHtml(a,articleHtml(original));const content=articleContent(original);if(content)fs.writeFileSync(path.join(articleDir,`${a.id}.json`),JSON.stringify(content),{mode:0o600});save();return send(res,201,{article:publicArticle(a)})}
if(s.role==='admin'&&req.method==='GET'&&route==='/api/users'){return send(res,200,{users:db.users.map(u=>({...u,keyEncrypted:undefined,keyHash:undefined,devices:db.devices.filter(d=>d.userId===u.id&&!d.blocked).length,lastLogin:db.logins.find(x=>x.userId===u.id)?.at||null}))})}
if(s.role==='admin'&&req.method==='POST'&&route==='/api/users'){const b=await body(req),k=makeKey(),u={id:id(),name:String(b.name||'Новый пользователь').slice(0,100),note:String(b.note||'').slice(0,500),telegramId:String(b.telegramId||'').trim().slice(0,64),deviceLimit:Math.max(1,Math.min(20,Number(b.deviceLimit)||2)),blocked:false,keyHash:digest(k),keyEncrypted:encrypt(k),created:new Date().toISOString()};db.users.push(u);save();log('Создание пользователя',me.name,address,u.name);return send(res,201,{user:{id:u.id,name:u.name,note:u.note,deviceLimit:u.deviceLimit,blocked:u.blocked},key:k})}
if(s.role==='admin'&&route.startsWith('/api/users/')&&req.method==='GET'){const u=db.users.find(x=>x.id===route.split('/')[3]);if(!u)return fail(res,404,'Пользователь не найден.');log('Просмотр ключа',me.name,address,u.name);return send(res,200,{user:{...u,keyHash:undefined,keyEncrypted:undefined,key:decrypt(u.keyEncrypted)},devices:db.devices.filter(d=>d.userId===u.id).map(d=>({...d,tokenHash:undefined})),logins:db.logins.filter(l=>l.userId===u.id).slice(0,60)})}
if(s.role==='admin'&&route.startsWith('/api/users/')&&req.method==='PATCH'){const u=db.users.find(x=>x.id===route.split('/')[3]);if(!u)return fail(res,404,'Пользователь не найден.');const b=await body(req);if(b.blocked!==undefined)u.blocked=!!b.blocked;if(b.deviceLimit!==undefined)u.deviceLimit=Math.max(1,Math.min(20,Number(b.deviceLimit)||1));if(b.name!==undefined)u.name=String(b.name).slice(0,100);if(b.note!==undefined)u.note=String(b.note).slice(0,500);if(b.telegramId!==undefined)u.telegramId=String(b.telegramId).trim().slice(0,64);if(b.rotate){const k=makeKey();u.keyHash=digest(k);u.keyEncrypted=encrypt(k);db.sessions=db.sessions.filter(x=>x.userId!==u.id);save();return send(res,200,{ok:true,key:k})}save();log(u.blocked?'Блокировка пользователя':'Обновление пользователя',me.name,address,u.name);return send(res,200,{ok:true})}
if(s.role==='admin'&&route.startsWith('/api/users/')&&req.method==='DELETE'){const uid=route.split('/')[3];db.users=db.users.filter(x=>x.id!==uid);db.devices=db.devices.filter(x=>x.userId!==uid);db.sessions=db.sessions.filter(x=>x.userId!==uid);save();log('Удаление пользователя',me.name,address,uid);return send(res,200,{ok:true})}
if(s.role==='admin'&&route.startsWith('/api/devices/')&&req.method==='PATCH'){const d=db.devices.find(x=>x.id===route.split('/')[3]);if(!d)return fail(res,404,'Устройство не найдено.');d.blocked=!!(await body(req)).blocked;db.sessions=db.sessions.filter(x=>x.userId!==d.userId);save();return send(res,200,{ok:true})}
if(route==='/api/'||route==='/api')return fail(res,404,'Не найдено.');
if(route.startsWith('/api/'))return fail(res,404,'Не найдено.');
const file=route==='/'?'index.html':path.basename(route);const allowed=['index.html','app.js','style.css','robots.txt','one-bg.png'];if(!allowed.includes(file))return fail(res,404,'Не найдено.');const fp=path.join(__dirname,'public',file);return send(res,200,fs.readFileSync(fp),{'content-type':file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.txt')?'text/plain; charset=utf-8':file.endsWith('.png')?'image/png':'text/html; charset=utf-8','x-robots-tag':'noindex, nofollow'});
}catch(e){console.error('request error:',e.message);return fail(res,500,PROD?'Внутренняя ошибка.':'Ошибка запроса: '+e.message)}
});
server.listen(PORT,HOST,()=>console.log(`0ne//hub запущен: http://${HOST}:${PORT}`));
