const fs=require('node:fs'),path=require('node:path');
const {sanitize,normalizeLegacyHtml}=require('../lib/content');
const dir=path.resolve(process.env.DATA_DIR||path.join(__dirname,'..','data'));
const store=path.join(dir,'store.json'),articleDir=path.join(dir,'articles');
if(!fs.existsSync(store)){console.error(`Не найдено хранилище ${store}; перенесите store.json и папку articles.`);process.exit(1)}
const db=JSON.parse(fs.readFileSync(store,'utf8'));for(const k of ['users','articles','sessions','devices','logins','audit','categories'])db[k]||=[];
fs.mkdirSync(articleDir,{recursive:true});const slugify=s=>String(s||'').toLocaleLowerCase('ru').replace(/[а-яё]/g,c=>({'а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ё':'e','ж':'zh','з':'z','и':'i','й':'y','к':'k','л':'l','м':'m','н':'n','о':'o','п':'p','р':'r','с':'s','т':'t','у':'u','ф':'f','х':'h','ц':'ts','ч':'ch','ш':'sh','щ':'sch','ъ':'','ы':'y','ь':'','э':'e','ю':'yu','я':'ya'}[c]||c)).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const names=new Map(db.categories.map(c=>[String(c.name||'').toLocaleLowerCase('ru'),c]));
function category(name){const key=String(name||'Без категории').trim().toLocaleLowerCase('ru');let c=names.get(key);if(!c){c={id:require('node:crypto').randomUUID(),name:key==='без категории'?'Без категории':name,slug:slugify(name)||`category-${db.categories.length+1}`,description:'',icon:'◈',sort_order:db.categories.length,hidden:false,created:new Date().toISOString()};while(db.categories.some(x=>x.slug===c.slug))c.slug+=`-${db.categories.length+1}`;db.categories.push(c);names.set(key,c)}return c;}
const categorySlugs=new Set();for(const [i,c] of db.categories.entries()){c.slug||=slugify(c.name)||`category-${i+1}`;const base=c.slug;let suffix=2;while(categorySlugs.has(c.slug))c.slug=`${base}-${suffix++}`;categorySlugs.add(c.slug);c.description||='';c.icon||='◈';c.sort_order??=i;c.hidden=!!c.hidden}
let changed=0;const articleSlugs=new Set();
for(const a of db.articles){let html=a.html||'';const file=path.join(articleDir,`${a.id}.html`);if(fs.existsSync(file))html=fs.readFileSync(file,'utf8');const normalized=sanitize(normalizeLegacyHtml(html));fs.writeFileSync(file,normalized,{mode:0o600});const cat=category(a.categoryName||a.category||db.categories.find(c=>c.id===a.categoryId)?.name||'Без категории');a.categoryId=cat.id;a.slug||=slugify(a.title)||`article-${a.id}`;const baseSlug=a.slug;let suffix=2;while(articleSlugs.has(a.slug))a.slug=`${baseSlug}-${suffix++}`;articleSlugs.add(a.slug);if(a.content){fs.writeFileSync(path.join(articleDir,`${a.id}.json`),JSON.stringify(a.content),{mode:0o600});delete a.content}a.description=String(a.description||'').slice(0,400);a.status=a.status==='published'?'published':'draft';a.hidden=!!a.hidden;a.updated||=a.created||new Date().toISOString();delete a.html;changed++;}
fs.writeFileSync(store,JSON.stringify(db,null,2),{mode:0o600});console.log(`Миграция завершена: ${changed} статей; категории: ${db.categories.length}. Пользователи, ключи, сессии и устройства сохранены.`);
